// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtSFEJ-JtQTXBAmWidWBg5B7-TBEDqM-I',
    appId: '1:869399523655:web:70e84570430db04a4b1c62',
    messagingSenderId: '869399523655',
    projectId: 'ation-d6c24',
    authDomain: 'ation-d6c24.firebaseapp.com',
    storageBucket: 'ation-d6c24.appspot.com',
    measurementId: 'G-RZC8F5ESGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVe7C4Y2R4kpkkEQ-jhSHXLaW_1GFuoBA',
    appId: '1:869399523655:android:cbade0446239e6664b1c62',
    messagingSenderId: '869399523655',
    projectId: 'ation-d6c24',
    storageBucket: 'ation-d6c24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ZT6ZJHfqPlCyYA2fzk7Edwp3ELqAK5Q',
    appId: '1:869399523655:ios:96659f0dccd0fd324b1c62',
    messagingSenderId: '869399523655',
    projectId: 'ation-d6c24',
    storageBucket: 'ation-d6c24.appspot.com',
    iosClientId: '869399523655-a0t30e76tqc6lgf3s9ile8ls9ihr7pjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectcrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1ZT6ZJHfqPlCyYA2fzk7Edwp3ELqAK5Q',
    appId: '1:869399523655:ios:96659f0dccd0fd324b1c62',
    messagingSenderId: '869399523655',
    projectId: 'ation-d6c24',
    storageBucket: 'ation-d6c24.appspot.com',
    iosClientId: '869399523655-a0t30e76tqc6lgf3s9ile8ls9ihr7pjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectcrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtSFEJ-JtQTXBAmWidWBg5B7-TBEDqM-I',
    appId: '1:869399523655:web:db2d96493f9aa9ed4b1c62',
    messagingSenderId: '869399523655',
    projectId: 'ation-d6c24',
    authDomain: 'ation-d6c24.firebaseapp.com',
    storageBucket: 'ation-d6c24.appspot.com',
    measurementId: 'G-N0K8V0W0DQ',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBtSFEJ-JtQTXBAmWidWBg5B7-TBEDqM-I',
    appId: '1:869399523655:web:59db0122185d1e0d4b1c62',
    messagingSenderId: '869399523655',
    projectId: 'ation-d6c24',
    authDomain: 'ation-d6c24.firebaseapp.com',
    storageBucket: 'ation-d6c24.appspot.com',
    measurementId: 'G-G7CFG3Y05N',
  );
}
